"""Add Bounties

Revision ID: 2e541a634aa6
Revises: c0b7b0d85296
Create Date: 2026-06-18 01:21:18.143167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e541a634aa6'
down_revision: Union[str, None] = 'c0b7b0d85296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bounties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('funder_id', sa.UUID(), nullable=False),
    sa.Column('github_issue_url', sa.String(length=512), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['funder_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('bounties')
    # ### end Alembic commands ###
