"""Initial Pivot

Revision ID: c0b7b0d85296
Revises: 
Create Date: 2026-06-18 01:09:54.172677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision: str = 'c0b7b0d85296'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('github_repo_url', sa.String(length=512), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_log_checked_at'), 'crawl_log', ['checked_at'], unique=False)
    op.create_index(op.f('ix_crawl_log_github_repo_url'), 'crawl_log', ['github_repo_url'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('github_repo_url', sa.String(length=512), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=False),
    sa.Column('expert_analysis', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('tech_stack', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('complexity', sa.String(length=50), nullable=False),
    sa.Column('revenue_model', sa.String(length=100), nullable=False),
    sa.Column('growth_potential_score', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('meta_title', sa.String(length=255), nullable=False),
    sa.Column('meta_description', sa.Text(), nullable=False),
    sa.Column('json_ld', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('github_stars', sa.Integer(), nullable=False),
    sa.Column('github_forks', sa.Integer(), nullable=False),
    sa.Column('last_commit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('license', sa.String(length=100), nullable=True),
    sa.Column('source_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('live_demo_url', sa.String(length=512), nullable=True),
    sa.Column('demo_video_url', sa.String(length=512), nullable=True),
    sa.Column('pitch_deck', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_rescanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_category'), 'listings', ['category'], unique=False)
    op.create_index(op.f('ix_listings_github_repo_url'), 'listings', ['github_repo_url'], unique=True)
    op.create_index(op.f('ix_listings_slug'), 'listings', ['slug'], unique=True)
    op.create_index(op.f('ix_listings_status'), 'listings', ['status'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=255), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fulfillment_status', sa.String(length=20), nullable=False),
    sa.Column('escrow_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_index(op.f('ix_listings_status'), table_name='listings')
    op.drop_index(op.f('ix_listings_slug'), table_name='listings')
    op.drop_index(op.f('ix_listings_github_repo_url'), table_name='listings')
    op.drop_index(op.f('ix_listings_category'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_crawl_log_github_repo_url'), table_name='crawl_log')
    op.drop_index(op.f('ix_crawl_log_checked_at'), table_name='crawl_log')
    op.drop_table('crawl_log')
    # ### end Alembic commands ###
