"""Add visibility

Revision ID: cc58336f1bc8
Revises: 2e541a634aa6
Create Date: 2026-06-20 22:55:52.669542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc58336f1bc8'
down_revision: Union[str, None] = '2e541a634aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('visibility', sa.String(length=20), nullable=False, server_default='private'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'visibility')
    # ### end Alembic commands ###
